SUPABASE_URL = "https://cpposqsqoxfdfmgtsqzd.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwcG9zcXNxb3hmZGZtZ3RzcXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MjMzNzgsImV4cCI6MjA2ODQ5OTM3OH0.AuxqaAJWbNG4jmW23kLl7hN9ixHPkQCAKz-1tIGmj68"
